language: node_js
node_js:
  - "10"

script:
  - npm install -g eslint tslint typescript eslint-config-airbnb  eslint-config-react-app eslint-plugin-flowtype eslint-plugin-import eslint-plugin-jsx-a11y eslint-plugin-react babel-eslint
  - cd backend
  - npm run lint
  - cd ..
  - cd frontend
  - npm install
  - npm run lint
